### ISSUE TITLE
Error on frontend and issue

### ISSUE THREAD

**Issue by SBHARIHARAN** [Daltonic/safehaven#4]
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (E:\Sample1\freshers\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (E:\Sample1\freshers\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (E:\Sample1\freshers\node_modules\webpack\lib\NormalModule.js:471:10)
    at E:\Sample1\freshers\node_modules\webpack\lib\NormalModule.js:503:5
    at E:\Sample1\freshers\node_modules\webpack\lib\NormalModule.js:358:12
    at E:\Sample1\freshers\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (E:\Sample1\freshers\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (E:\Sample1\freshers\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at E:\Sample1\freshers\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (E:\Sample1\freshers\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (E:\Sample1\freshers\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (E:\Sample1\freshers\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (E:\Sample1\freshers\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at E:\Sample1\freshers\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
E:\Sample1\freshers\node_modules\react-scripts\scripts\build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (E:\Sample1\freshers\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (E:\Sample1\freshers\node_modules\webpack\lib\NormalModule.js:417:16)
    at E:\Sample1\freshers\node_modules\webpack\lib\NormalModule.js:452:10
    at E:\Sample1\freshers\node_modules\webpack\lib\NormalModule.js:323:13
    at E:\Sample1\freshers\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at E:\Sample1\freshers\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (E:\Sample1\freshers\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at E:\Sample1\freshers\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
it is the error comes when I run the Yarn start

**Comment by Musak2** [comment]
I have the same issue. Did you manage to fix this somehow, please?
